### ISSUE TITLE
Grails 2.5.0> problem

### ISSUE THREAD

**Issue by GilbertHofstaetter** [vaadin-for-grails/vaadin7-plugin#2]
When using Grails 2.5.0 and beyond with `com.github.vaadin-for-grails:vaadin7:LATEST`  (v.2.2) the following error appears:

**Caused by BeanInstantiationException: Failed to instantiate [org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessor]: Factory method 'asyncAdvisor' threw exception; nested exception is java.lang.IllegalArgumentException: @EnableAsync annotation metadata was not injected**

This issue is described under http://vijava.blogspot.co.at/2012/12/enableasync-annotation-metadata-was-not.html

Changing `context.'component-scan'('base-package': '*')` in your Vaadin7GrailsPlugin.groovy class in method `doWithSpring`  to `context.'component-scan'('base-package': 'org.vaadin')`  solves this issue.

Grails 2.5.0 in combination with  `com.github.vaadin-for-grails:vaadin-core:1.0-SNAPSHOT`  works fine.

**Comment by stephangrundner** [comment]
Changing the `base-package` from `*` to `org.vaadin` is not a solution, moreover this is not a plugin related problem!

The asterisk is just a default if no packages were specified; Have a look at the following code (Line 47-51 from `Vaadin7GrailsPlugin.groovy`):

``` groovy
        def packages = application.config.grails.spring.bean.packages
        if (packages.isEmpty()) {
            xmlns context:"http://www.springframework.org/schema/context"
            context.'component-scan'('base-package': '*')
        }
```

You've to specify the package(s) to be scanned by your own in the `grails-app/conf/Config.groovy` file.
Simply put your package name(s) in the `grails.spring.bean.packages` variable like followed.

``` groovy
// packages to include in Spring bean scanning
grails.spring.bean.packages = ['tld.yourcompany', 'tld.othercompany']
```

Read more [here](http://mrhaki.blogspot.co.at/2014/08/grails-goodness-use-spring-java.html).

Thanks for your support.

**Comment by stephangrundner** [comment]
Updated the plugin! So Grails 2.5.0 is officially supported now and Vaadin release 7.5.5 is used.
The package scanning now excludes all classes from "org.springframework" by default, so you don't even have to specify custom packages in your `Config.groovy` file.

``` groovy
        def packages = application.config.grails.spring.bean.packages
        if (packages.isEmpty()) {
            xmlns context:"http://www.springframework.org/schema/context"
            context.'component-scan'('base-package': '*') {
                context.'exclude-filter'(type: 'regex', expression: /org\.springframework\..*/)
            }
        }
```
